// Package revisiontypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package revisiontypes

import (
	"time"
)

// DeclareInput What an engine is asked with when it reports what it needs. It carries the engine's own spec block and the pipeline root, because an engine declares its resources before any record exists to name.
type DeclareInput struct {
	// Repos The pipeline's repositories by name, each a directory under the root, for a compute engine that keys a cache on what the run is built from - the same repositories the revision hashes. A state engine ignores them.
	Repos *[]DeclaredRepo `json:"repos,omitempty"`

	// Root The pipeline root on the local filesystem, for an engine whose spec names workspace files to read at declare time. Optional, so an engine that reads nothing keeps validating without it.
	Root *string `json:"root,omitempty"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`

	// Stages The pipeline's stages by name, each with its substages, for a compute engine that renders the run as jobs. A state engine ignores them; they are here so the one declare input the core sends validates against every engine's schema.
	Stages *[]DeclaredStage `json:"stages,omitempty"`
}

// DeclareOutput What an engine needs to exist. An engine with no infrastructure returns an empty list.
type DeclareOutput struct {
	Resources []Resource `json:"resources"`
}

// DeclaredRepo One repository of the pipeline, by the directory name it is checked out under.
type DeclaredRepo struct {
	Name string `json:"name"`
}

// DeclaredStage One stage of the pipeline, by name, with its substages.
type DeclaredStage struct {
	// DisplayName What to call this stage where a person reads it. Absent means the caller derives a title from the name, so a pipeline that says nothing still reads as words rather than as an identifier.
	DisplayName *string             `json:"displayName,omitempty"`
	Name        string              `json:"name"`
	Substages   *[]DeclaredSubstage `json:"substages,omitempty"`
}

// DeclaredSubstage One substage of a stage, by name.
type DeclaredSubstage struct {
	// DisplayName What to call this substage where a person reads it. Absent means the caller derives a title from the stage and substage names.
	DisplayName *string `json:"displayName,omitempty"`
	Name        string  `json:"name"`

	// Needs Substages of the same stage that must advance before this one runs, for a compute engine that renders one job per substage and has to wire the order between them. Absent means none.
	Needs *[]string `json:"needs,omitempty"`

	// Uses Substages of EARLIER stages, as <stage>/<substage>, whose built artifacts this one reads, for a compute engine that carries files between jobs and can then carry only these. Absent means everything every earlier stage built.
	Uses *[]string `json:"uses,omitempty"`
}

// Resource Something an engine needs to exist. Declared by engines, realized by managers.
type Resource struct {
	// Kind Resource kind, for example directory or table.
	Kind string `json:"kind"`

	// Name Unique name within the kind.
	Name string `json:"name"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`
}

// Revision A tuple of repo commits at a moment in time. The id is derived from the tuple, so the same commits always give the same revision.
type Revision struct {
	// CreatedAt When the revision was resolved.
	CreatedAt time.Time `json:"createdAt"`

	// Dirty Repos with uncommitted changes, sorted.
	Dirty *[]string `json:"dirty,omitempty"`

	// Id Content derived identifier. Suffixed with -dirty when any repo has uncommitted changes, because an uncommitted break must not reuse a passing run.
	Id string `json:"id"`

	// Repos Repo name to commit SHA. Empty when the pipeline declares no repos.
	Repos *map[string]string `json:"repos,omitempty"`
}

// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
type Spec map[string]interface{}

// StateGetInput Read one record, or list under one kind when key is a prefix.
type StateGetInput struct {
	// Key Identifies the record within its kind. Nested keys use slashes.
	Key *string `json:"key,omitempty"`

	// Kind The record family. revision, run or owned.
	Kind string `json:"kind"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`
}

// StateGetOutput The result of a read. A missing record is found false, never an error.
type StateGetOutput struct {
	Found   bool    `json:"found"`
	Payload *string `json:"payload,omitempty"`
}

// StateListOutput The keys under one kind.
type StateListOutput struct {
	Keys []string `json:"keys"`
}

// StatePutInput Write one record.
type StatePutInput struct {
	Key  string `json:"key"`
	Kind string `json:"kind"`

	// Payload The record body. A string, not bytes. A byte array marshals to base64 and the generated MCP schema rejects it, which broke every state write while passing in process.
	Payload string `json:"payload"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`
}
