// Package revisiontypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package revisiontypes

import (
	"time"
)

// DeclareOutput What an engine needs to exist. An engine with no infrastructure returns an empty list.
type DeclareOutput struct {
	Resources []Resource `json:"resources"`
}

// Resource Something an engine needs to exist. Declared by engines, realized by managers.
type Resource struct {
	// Kind Resource kind, for example directory or table.
	Kind string `json:"kind"`

	// Name Unique name within the kind.
	Name string `json:"name"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`
}

// Revision A tuple of repo commits at a moment in time. The id is derived from the tuple, so the same commits always give the same revision.
type Revision struct {
	// CreatedAt When the revision was resolved.
	CreatedAt time.Time `json:"createdAt"`

	// Dirty Repos with uncommitted changes, sorted.
	Dirty *[]string `json:"dirty,omitempty"`

	// Id Content derived identifier. Suffixed with -dirty when any repo has uncommitted changes, because an uncommitted break must not reuse a passing run.
	Id string `json:"id"`

	// Repos Repo name to commit SHA. Empty when the pipeline declares no repos.
	Repos *map[string]string `json:"repos,omitempty"`
}

// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
type Spec map[string]interface{}

// StateGetInput Read one record, or list under one kind when key is a prefix.
type StateGetInput struct {
	// Key Identifies the record within its kind. Nested keys use slashes.
	Key *string `json:"key,omitempty"`

	// Kind The record family. revision, run or owned.
	Kind string `json:"kind"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`
}

// StateGetOutput The result of a read. A missing record is found false, never an error.
type StateGetOutput struct {
	Found   bool    `json:"found"`
	Payload *string `json:"payload,omitempty"`
}

// StateListOutput The keys under one kind.
type StateListOutput struct {
	Keys []string `json:"keys"`
}

// StatePutInput Write one record.
type StatePutInput struct {
	Key  string `json:"key"`
	Kind string `json:"kind"`

	// Payload The record body. A string, not bytes. A byte array marshals to base64 and the generated MCP schema rejects it, which broke every state write while passing in process.
	Payload string `json:"payload"`

	// Spec Engine specific configuration. The core model fixes the shape of a revision. Each engine keeps this block for its own internals, so ci-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
	Spec *Spec `json:"spec,omitempty"`
}
